### ISSUE TITLE
Emoji is broken when using Mozilla Firefox on Windows

### ISSUE THREAD

**Issue by Camoen** [johnchinjew/johnchinjew.github.io#4]
https://github.com/jawnyawns/jawnyawns.github.io/blob/a97e88298c5df04e1aa38e7bfeb7b1417d902dbb/index.html#L33

Please update to improve the CX for all users!

**Comment by johnchinjew** [comment]
Proposed fix: ~~https://github.com/jawnyawns/jawnyawns.github.io/commit/aa27290a844d43f58cb154117506c28c180597c0~~ https://github.com/jawnyawns/jawnyawns.github.io/commit/2395e44ad1ba351b3b6f55ec136ddbfff74a2d6e

Pending verification. @Camoen can you check if the emoji is rendering now?

**Comment by johnchinjew** [comment]
Confirmed the emoji is now visible for FF on Windows.
